### ISSUE TITLE
How to PXE boot

### ISSUE THREAD

**Issue by dmatthewsbnd251** [Tomas-M/linux-live#103]
How do I pxe boot? Here is my current configuration

DEFAULT linux
LABEL linux
KERNEL /images/debian-live/linux/boot/vmlinuz 
INITRD /images/debian-live/linux/boot/initrfs.img

It ends up saying, "looking for linux data on /linux...." and then fails.  It otherwise works fine to boot directly from the iso.

**Comment by Kevin87114** [comment]
Do you have a DHCP Server, a PXE Client set for PXE Boot and TFTP server running to send the boot image to the Client?.
You will want to edit your dhcpd.leases file so the server knows what it's communicating with.

You can read this for a primer:
[](https://www.freebsd.org/doc/handbook/network-diskless.html)

Here is the rudimentary functions that you can place in bash script to automate the process.
This code is part of a larger script I wrote with a state machine.  Edit accordingly. 

Note: Remove the double quotes around the comments. For some reason the 'insert code' function translates # comments into large text. The "# comment"  keeps the comments small.
`
DHCPD_LEASES_FILE="/var/lib/dhcp/dhcpd.leases" # path to dhcpd.leases file
MAC_addr=XX:yy:XX:yy:XX:yy # Enter MAC of PXE Client
MAC_addr="${MAC_addr,,}" # Make all lowercase and send to dhcpd.leases file editor function

"# dhcpd.leases MAC Address File Editor Function"
dhcpdLeasesEdit(){
clear
ExistingMACaddr="" # The MAC address in dhcpd.leases file before new MAC address in written to file
"# Edit dhcpd.leases file"
if [[ ! -e $DHCPD_LEASES_FILE ]]; then # Test for file exists
	printf "The required dhcpd.leases file does not exist!"
	sleep 2
	state="QUIT" # Exit
else # Read file
	clear
	exec {FD}<"${DHCPD_LEASES_FILE}" # open file for read, assign descriptor
	while read -r -u ${FD} HDW ETH MAC; do
		if [[ $HDW == "hardware" ]] && [[ $ETH == "ethernet" ]]; then
			exec {FD}<&- # Close file
			ExistingMACaddr=$MAC
			# Replace MAC Address with user-supplied MAC Address
			sudo sed -i "s|hardware ethernet $ExistingMACaddr|hardware ethernet $MAC_addr;|" $DHCPD_LEASES_FILE
			break
		fi
	done
fi
state="DHCP_SERVER_RESTART" # Restart dhcp server after dhcpd.leases MAC address file edit
from_state="DHCP_LEASES_EDIT"
return 0
}

"# DHCP Server Restart Function"
dhcpServerRestart(){
clear
"# Restart dhcp server after dhcpd.leases MAC address file edit"
sudo service isc-dhcp-server restart
state="DHCP_SERVER_STATUS"
from_state="DHCP_SERVER_RESTART"
return 0
}`

Insert `MAC_addr="${MAC_addr,,}"' since the MAC needs to be lower case, else an internal error will occur and cause isc-server to create a new file from a .~leases backup.

I hope this helps.

**Comment by SircasticFox** [comment]
> 
> 
> How do I pxe boot? Here is my current configuration
> 
> DEFAULT linux
> LABEL linux
> KERNEL /images/debian-live/linux/boot/vmlinuz
> INITRD /images/debian-live/linux/boot/initrfs.img
> 
> It ends up saying, "looking for linux data on /linux...." and then fails. It otherwise works fine to boot directly from the iso.

I'm facing the same issue with Ubuntu 20.04. Has anybody figured this out yet?

**Comment by Thatoo** [comment]
I have the same issue with the same config : 
```
DEFAULT linux
LABEL linux
KERNEL boot/debian-live/linux/boot/vmlinuz
INITRD boot/debian-live/linux/boot/initrfs.img
```

and if I modify the config to

```
DEFAULT linux
LABEL linux
KERNEL boot/debian-live/linux/boot/vmlinuz
APPEND netboot=nfs ip=dhcp nfsroot=192.168.2.1:/srv/tftp/boot/debian-live/linux initrd=boot/debian-live/linux/boot/initrfs.img
```
then I get the following error 
```
* Setting up network
ifconfig: bad address ''
route: resolving
....
```
![image](https://user-images.githubusercontent.com/464782/124092516-3d46eb80-da57-11eb-98d3-3c6ae321b6ea.png)

so it seems like dhcp is not working even though it does work when I boot from ubuntu image etc. It's just not working when I boot image I have made using linux-live.

@Kevin87114 I don't understand the solution you offer. Should we do that in the system before creating the iso image with the help of linux-live?

Is there any idea to solve this problem?

**Comment by hoomanjavadpoor** [comment]
same issue for me!!!

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.

**Comment by brian-anderson01** [comment]
Has anyone figured this out? I've been trying to get PXE boot working for a week now and still can't get it working. I'm having the issue where it says "looking for linux data on /linux...." and then fails. Is there something I need to change in my PXE default file?

**Comment by Tomas-M** [comment]
If you get so far, then it means your PXE boot works just fine, and then probably network setup fails. Make sure you have all network drivers in your initrd (see config file, there is an option for that, set NETWORK=true)
https://github.com/Tomas-M/linux-live/blob/master/config

**Comment by brian-anderson01** [comment]
> If you get so far, then it means your PXE boot works just fine, and then probably network setup fails. Make sure you have all network drivers in your initrd (see config file, there is an option for that, set NETWORK=true) https://github.com/Tomas-M/linux-live/blob/master/config

I recreated a zip of my file using the scripts and ensured that I had network set to true, but now I have no vmlinuz file in the boot folder. Is this normal? Not really sure how I can boot without the kernel.

**Comment by DoktorJ** [comment]
@Tomas-M I'm having the same issue; I set `NETWORK=true`, but still get the same errors. I can successfully serve (TFTP) and boot (client) a vanilla Debian netboot installer on the same device, but I edited my `config`, ran `./build` again, and still no joy.

I booted my "host" device (that I built the live image on) from PXE, and it has the same problem, so it _shouldn't_(?) be an issue of not having the network drivers available? When booted to its Debian install that I used as the base for the live image, it loads the appropriate modules and connects to the network just fine, so the base OS has the modules available.

I'd ideally like it to connect to NFS and pull `01-core.sb` from there, but I don't think that's going to be a thing if it can't even see its ethernet adapter properly (or otherwise get a DHCP IP despite having done so in the PXE part of the boot).

**Comment by DoktorJ** [comment]
For reference, my `pxelinux.cfg/default` entry is as follows (all files specified are in the tftp root, hence no path)

```
KERNEL vmlinuz
APPEND vga=792 initrd=initrfs.img root=/dev/nfs ip=dhcp nfsroot=10.0.28.240:/boot ro
```

**Comment by trigger1154** [comment]
Same issue here. boots the initrd no problem but then that wants to find the data in the linux folder but cant because it is on nfs. I Even tried this in the root folder for pxelinux. Anyone figure this out?

**Comment by trigger1154** [comment]
I tried installing libnfs-utils on the Linux Mint os I ran live kit on. Still no change. If I don't include network options in the pxelinux menu it hangs on looking for data and errors. If I include NFS options and set ip=dhcp it says bad address when trying to connect.

Current menu

MENU LABEL Linux Live Wiper Test 2
    KERNEL /Tools/lvwiper/boot/vmlinuz 
    APPEND vga=792 netboot=nfs ip=dhcp initrd=/Tools/lvwiper/boot/initrfs.img root=/Tools/lvwiper/ nfsroot=192.168.1.3:/Tools/lvwiper ro
