### ISSUE TITLE
initramfs drivers set might be incomplete

### ISSUE THREAD

**Issue by viert** [Tomas-M/linux-live#117]
Hi Tomas,

I've been developing a provisioning service and the discovery part of that is based on a pxe-based CentOS image built with linux-live toolkit. The thing is great, thank you for a great product. I've got some issues recently though, the thing is, on some hardware the image won't boot stuck at `Probing EDD (edd=off to disable)...ok`. A long investigation revealed that it had nothing to do with the EDD, and this "ok" was a best indicator of that, so the booting process stuck at some point after that. At some point I decided to make changes to create_initramfs script: I removed all the selective driver installation part and made it install all the drivers it could find in the $LKM/kernel/drivers directory. This helped with that particular piece of hardware perfectly so I was happy until some hours later when colleagues figured out it stopped booting on other hardware: first it was freezing at "Probing hardware" for a couple of minutes (including all the drivers was a bad idea?) and the following moment it crashed unable to mount /memory/data like it couldn't load the iso.

Is there a way to create a universal image capable of booting on nearly any hardware?

Thanks

**Comment by Tomas-M** [comment]
Actually create_initramfs script is my attempt to prepare universal selection of drivers.
But it is fairly possible that I've missed something.

If you find what particular kernel drivers (.ko files in $LKM/kernel/drivers/ directory) make the difference, then you can let me know and I will consider including them in create_initramfs script. 

To find them, you can try adding just several extra directories with drivers, if that doesn't help then remove them and add different extra directories, .... until it works.

**Comment by viert** [comment]
So there's no easier way, I see. Will follow this approach and hopefully find something that is missing.

**Comment by Tomas-M** [comment]
You can find some hints this way:
- include all kernel drivers and boot on the computer where it boots OK
- login, and kill all possible processes
- run this command few times:

    rmmod $(lsmod)

This will unload all loaded drivers from memory, except those ones in use. If we assume that the driver which is essential on your computer needs to be loaded all the time, it will stay loaded. Then you can finally use just `lsmod` to list the modules which remain loaded and maybe you will be able to identify which one is the necessary one. Make sure you are not using USB keyboard since it could unload usb drivers for it and in that case you wouldn't be able to type anything anymore :)

**Comment by viert** [comment]
Sorry for the delay,
I have tried to reduce the number of drivers as you suggested using a kind of binary search, haha =) It took too long and I was a bit pressed for time so I tried to switch to a Dracut-based Fedora-style livecd. No issues with any piece of hardware we have so far, somehow Dracut initrd copes with it. The image turns out to be much bigger though. 

I'll probably return to this task, as for now I better close the issue. Thank for your help!
