### ISSUE TITLE
Compute hash of USB drive contents

### ISSUE THREAD

**Issue by DNTM2802** [Tomas-M/linux-live#142]
I would like to compute an hash of the usb drive (/run/initramfs/memory/data) right before shutdown, and check it on the startup, in order to check the USB drive integrity and guarantee that the contents weren't manually changed. Is that possible? If so, which are the right places in the scripts to do so?
Thank you

**Comment by Tomas-M** [comment]
In order to compute hashes on shutdown, you will probably need to do it in the shutdown script (before it unmounts the usb drive): /run/initramfs/shutdown

If you like to make changes to this script permanent, you will need to unpack the initramfs image (/slax/boot/initrfs.img), modify the script and then pack the initramfs back. Note that if you need to use any tool for that, you will need to add the binaries to the initramfs image as well. If you are happy just with md5sum, sha512sum or similar, you can use busybox which has those commands included. (precompiled busybox binary in linux-live-kit has it included)

In order to check during startup, you will need to add your checks in the init script, probably just after the usb is mounted:
/run/initramfs/init
The same applies like above.

**Comment by DNTM2802** [comment]
I'm doing `ls -alR /run/initramfs/memory/data | sha1sum` right at the beginning of the shutdown script, but during shutdown, it says `ls: /run/initramfs/memory/data: No such file or directory`, so I guess the USB is already unmounted before the shutdown script?
But right before that I do `df | grep /run/initramfs/memory/data | awk '{ print $1 }'` and it returns `/dev/sdb1`, which contradicts what I said...

**Comment by DNTM2802** [comment]
I'm doing `ls -alR /run/initramfs/memory/data | sha1sum` right at the beginning of the shutdown script, but during shutdown, it says `ls: /run/initramfs/memory/data: No such file or directory`, so I guess the USB is already unmounted before the shutdown script?
But right before that I do `df | grep /run/initramfs/memory/data | awk '{ print $1 }'` and it returns `/dev/sdb1`, which contradicts what I said...

**Comment by Tomas-M** [comment]
Once you are in the shutdown script, the root is attached to /oldroot.
Check /oldroot/run/initramfs/memory/data (only while you are in the shutdown script execution)

You can put the following line to the shutdown script so you can run shell for further debugging:
`/bin/sh </dev/tty >/dev/tty 2>&1`
