### ISSUE TITLE
Fluxbox modification

### ISSUE THREAD

**Issue by thenoobtester** [Tomas-M/linux-live#151]
Hi,

I have been using slax for a year now and love it. I saw you made a modification to Fluxbox for the "start menu" which is great. Do you think you could add a feature to Fluxbox since it seems an abandoned project and doesn't take feature request anymore. It would be to allow re-ordering window icons in the iconbar just like you would with browser tabs.

This feature has been requested for the past 17 years (https://sourceforge.net/p/fluxbox/feature-requests/94/). I know it's not directly related to Slax but since a lot is configured for Slax I thought a modified version of Fluxbox with that feature specifically for Slax would be awesome.

Looking at the code I found the function which allows cycling focus with Alt-Tab (https://github.com/fluxbox/fluxbox/blob/master/src/FocusControl.cc --> FocusControl::cycleFocus line 96) but I don't know how to do the same to move the window before or after it's neighbour window in the taskbar/iconbar because I don't know C++. 

Thank you for your help.

**Comment by thenoobtester** [comment]
No more relevant.

**Comment by Tomas-M** [comment]
For some reason I overlooked this issue.
What I did for FluxBox in Slax is that I modified source code of fluxbox to show a different graphics (four squares instead of triangle) for a standard 'button' (which was previously supported by fluxbox. So I basically did not change any functionality of fluxbox, just the appearance of the 'button'.
