### ISSUE TITLE
Plymouth Theme Not Showing

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#176]
I have installed plymouth and set a theme as default.

However in the generated ISO, the theme does not load on boot.

I have added the splash kernel boot parameter with no luck.

What am I doing wrong please?

**Comment by Tomas-M** [comment]
linux-live ignores your plymouth settings, and there is actually no plan to support it, I am sorry

**Comment by bert003** [comment]
May I ask how these settings are ignored please? Is it in vmlinuz?

**Comment by Tomas-M** [comment]
If I understand it correctly, plymounth works this way:
- it adds splash screen to initrd
- it adds some binaries or other support for loading of the splash screen again to initrd
- when your OS boots, initrd starts, some binary loads the splash screen image, etc

But if you use linux-live, the entire initrd from your distro is ignored, since linux-live creates its own initrd. So for that reason it ignores your settings.

**Comment by bert003** [comment]
Now I understand perfectly. Thanks for the detailed explanation.

**Comment by bert003** [comment]
Allow me another question please. My plymouth is in the core sb module. Therefore I guess I need to load the necessary modules in the initrd to then be able to call plymouth from the core bundle.

I do not require any images to be present in the generated initrd. Any ideasl which modules are required please?

**Comment by Tomas-M** [comment]
I am afraid I don't know
