### ISSUE TITLE
how about  overlayfs?

### ISSUE THREAD

**Issue by boslad** [Tomas-M/linux-live#21]
Hi  Tomas-M,
   How about replacing AUFS with overlayfs? I  think that overlayfs is better,simpler ……than AUFS.

**Comment by Bindea** [comment]
Apart from being more modern and less of a need to patch the kernel overlayfs is supposed to be much faster.

I'm guessing it would make it compatible with more Ditro's.

**Comment by Bindea** [comment]
http://bear.alienbase.nl/cgit/liveslak/tree/make_slackware_live.sh
http://bear.alienbase.nl/cgit/liveslak
https://docs.slackware.com/slackware:liveslak

Does linux-live work with Slackware 14.2 ?

AlienBob is using overlayfs for his make_slackware_live script , maybe the code for that could be incorporated into linux-live to give users a choice of either Aufs or overlayfs?

**Comment by boslad** [comment]
@Bindea I think it is good to let users have a choice of Aufs or  overlayfs.

**Comment by luis-lavaire** [comment]
Yes, overlayfs is faster and newer. I think it should be added by default, or at least, let the users decide.

**Comment by Bindea** [comment]
Searching Google for overlayfs Vs Aufs seems to bring up a lot of results of people arguing what one is best.

The new Quirky 8.2 linux release has dropped overlayfs  and moved back too Aufs

http://distro.ibiblio.org/quirky/quirky6/amd64/releases/xerus-8.2/release-xerus64-8.2.htm
http://barryk.org/news/?viewDetailed=00591

Maybe Aufs is better?

**Comment by luis-lavaire** [comment]
Overlayfs was [merged](https://github.com/torvalds/linux/commit/e9be9d5e76e34872f0c37d72e25bc27fe9e2c54c) into mainline kernel, whereas aufs wasn't because it was a very [complex code](https://lwn.net/Articles/327738/).
You have to **tweak** and compile the kernel by yourself if you want support for aufs. As I see it, overlayfs is the future, and is considerably better than aufs; even with the possible bugs you could find on it, it's [faster](https://wiki.gentoo.org/wiki/OverlayFS), has a wider adoption (just take a look on docker) and, well, it's in mainline kernel.

@Bindea, for me, overlayfs is better in almost every case.

**Comment by Bindea** [comment]
Thank you for explaining. :)

Tomas-M doesn't seem to be that active. :(

**Comment by luis-lavaire** [comment]
You're welcome. BTW, you can look to [this](https://github.com/ivandavidov/minimal) or [this](https://github.com/ivandavidov/minimal-linux-script) project and start your own from there. ;)

**Comment by Bindea** [comment]
I'm not that clever. :)

**Comment by luis-lavaire** [comment]
I can help.

**Comment by Bindea** [comment]
Thanks but  to be honest stripped down Linux is not my thing. :)

I'd rather do a full install of something debian based and then use Tomas-M script to convert it to a live disk to save all the time and hassle.

**Comment by Bindea** [comment]
linux-live could do with an official forum so we could help each other out.

**Comment by johndah4x0r** [comment]
Maybe I have a solution... I am working on a fork to *implement* OverlayFS support, with two branches for each FS supported. As long as the transtion goes as "planned".

**Comment by luis-lavaire** [comment]
I can help in that. I need a tool like that to make my work easier. @johndah4x0r do you need some help?

**Comment by johndah4x0r** [comment]
No, I am trying to "hard-code" OverlayFS support on the livekitlib file and on the init script. Since I found out that appending bundles to an overlay filesystem was way too hard, so I thought of something like this:

1) Delete line: init_ aufs and replace it with modprobe_overlay.

2) "Hard-code" both mounting all bundles and overlay all bundles as lower, and the changes as both upperdir and workdir, into a function; prepare_overlay.

3) Implement them to init.

**Comment by johndah4x0r** [comment]
I made 2 separate branches for each.
It's really difficult to implement OverlayFS support, since it doesn't support adding branches on the fly!
So, I resorted to mount all in one line, but /bin/sh is too stubborn, so it will take me some time to find a work-around.

**Comment by johndah4x0r** [comment]
But, I didn't get any errors at all, until it was the time to "unify" all branches, this error came:
`sh: cannot execute 'mount': Argument list too long!`

**Comment by godane** [comment]
I updated you overlayfs-testing code in my live-kit-improved branch. Your code was trying to mount every folder in the mounted squashfs when you should only be using /memory/bundles/bundles.sb. You need '-maxdepth 1 -name "*.${BUND_EXT}" | sort' in get_lowerdirs function. I also get rid of your sed code since it was removing one of my modules for some reason and it wasn't need to work.
Hope this helps.

https://github.com/godane/linux-live-overlay/tree/live-kit-improved

**Comment by johndah4x0r** [comment]
I looked at your code, and it seems like I wanna merge it, but the "$NOCHANGES" bit got me alarming... Since changes and work must be in a POSIX-compatible FS (and more alarming, the same filesystem!), it might be a little bit problematic to point all to "$DATA"...
I suggest; DATA in prepare-overlay is replaced with a tmpfs mountpoint.

But, I have a plan to merge your code to my overlayfs-testing branch.
Feel free to contribute and/or submit suggestions;
Tomas *(the actual host)* is not as active as *"we"* do...

## FYI:
Debian Jessie DOES NOT support OverlayFS!

**Comment by johndah4x0r** [comment]
And please note, AGAIN!:
OverlayFS does NOT support remounting and/or appending branches on-the-fly! That's a huge problem when we want to add bundles without doing some fancy tweaks on the code...

**Comment by johndah4x0r** [comment]
And FYI:
I added in the `sed "$ d"` code for some reason; is that in my tests, there was a trailing column character after i bechmarked the get_lowerdirs function, and that  variable manipulations doesn't help either (note, this is Busybox ash), i added the `sed` code, in fear that `mount` might spit out a !!HECK!! a lot of errors...

**Comment by johndah4x0r** [comment]
But feel free to fork, contribute, or even ask for access to my mainline *overlayfs-testing* branch, since I would like to have some help...

**Comment by johndah4x0r** [comment]
And I moved the whole repo to my new repo; livekit-improved (i can finally open up my repo, contrib(s) welcome! :P)

**Comment by johndah4x0r** [comment]
For those who want, they (or even me) can open a separate issue/discussion.
### Just let me know! :P

**Comment by johndah4x0r** [comment]
I just opened a new issue in my own and/or new repo.
Since this might get overcrowded with a !!HECK!! of a lot of comments, and
there is a higher chance I will answer to the comments.

**Comment by Tomas-M** [comment]
I tried overlayfs and I was unhappy with it, it basically didn't work for me any good. So I refuse using it for linux live kit

**Comment by johndah4x0r** [comment]
Uhmm... I'm still working on it, and got almost flawless results in Ubuntu 16.04 (xenial) root base.

**Comment by johndah4x0r** [comment]
And @Tomas-M, by the way, I implemented OverlayFS as a fallback option if the user doesn't have the option to implement/use AUFS, or if he/she might be too lazy do compile all from scratch.

**Comment by Tomas-M** [comment]
If you can provide working patch with just small necessary changes, I can consider it, but no promises :)
