### ISSUE TITLE
ISO and ZIP unbootable

### ISSUE THREAD

**Issue by maccagnan** [Tomas-M/linux-live#237]
Systems: Devuan Chimaera & Alpine Linux Edge
Linux Live Scripts 2.9

Hi,

I created two live ISOs, one on Devuan Chimaera and one on Alpine Linux.
In both cases, I haven't got any problem during the live system creation.
However, in both cases, after I DDed the ISOs on a USB stick, it won't booth (GRUB just goes to the boot menu).
The same happens if I copy the .ZIP file on the USB and run the bootinst.sh script (note that I mount the USB mount /dev/sdb -o exec /mnt/usb to avoid permission problems). Again, the output is successful, but the USB won't boot.
I tried both formatting the USB to ext4 and FAT32.
However, if I boot the live distros iso from the HD or in frugal mode from the HD using grub, they both boot fine.
I'm sure the USB is fine since I use it to test live ISOs all the time.
Any suggestions as to how troubleshoot the problem?

Thanks.
 
UPDATE: I tried to boot the iso with ventoy and it gives me an error: fail to load idlinux.c32. The slax live cd boots fine on the same usb. I don't know if it helps.

**Comment by maccagnan** [comment]
Not that it's related, but i also noticed that syslinux.cfg stanza is 
LABEL default
MENU LABEL Run Linux
KERNEL /No-X/boot/vmlinuz
APPEND vga=769 initrd=/No-X/boot/initrfs.img load_ramdisk=1 prompt_ramdisk=0 rw printk.time=0 apparmor=0 perch

LABEL default
MENU LABEL Run Linux debug
KERNEL /No-X/boot/vmlinuz
APPEND vga=769 initrd=/No-X/boot/initrfs.img load_ramdisk=1 prompt_ramdisk=0 rw printk.time=0 apparmor=0 debug perch

where the kernel should be vimlinuz-edge since that's the kernel which correctly is installed in the /No-X/boot dir

**Comment by equetzal** [comment]
I recommend you reading this page https://www.slax.org/starting.php
The way in which you're installing Slax, is not correct. Follow the intructions of the link.

**Comment by maccagnan** [comment]
@equetzal 
I'm not using Slax, just used the Linux Live Kit to create my own live cd from Devuan and Alpine Linux.
Por cierto, saludos desde la Baja.

**Comment by equetzal** [comment]
The installation method is the same for Slax and Linux-Live created kits, this is because Slax is created using linux live, so in both cases you'll be needing to follow the method of copying the contents to the USB and then running the bootinst script. 
Also, if you need UEFI support it's required to format your USB on FAT32 (syslinux have a ext4 UEFI compatible boot, but it still not supported by linux-live), so ext4 won't help to boot. 
Now, for the [ldlinux.c32](https://github.com/Tomas-M/linux-live/blob/master/bootfiles/ldlinux.c32), you need to make sure that your ISO contain all this files to boot https://github.com/Tomas-M/linux-live/tree/master/bootfiles
You can decompress the .zip and modify it manually to add the missing files, and then recompress it to re-distribute it as you need it. Also, you need to have present the [mbr.bin](https://github.com/Tomas-M/linux-live/blob/master/bootfiles/mbr.bin) file in order to run bootinst.sh succesfully and be able to boot on Legacy BIOS. 
Let me know if all of this help :), It's highly likely that something was missing during the creation of your live kit :p 

Saludos hasta la baja! :D

**Comment by maccagnan** [comment]
@equetzal
Thanks for your help, it's much appreciated.
What I did was following the readme instructions to the letter, using all the default seetings. 
I tried both with Devuan and Alpine.
The squashfs system was created without any problem, and it boots fine in frugal mode, so I assume the error lies elsewhere, like you said, some file must be misplaced or I missed a step.
I tried both booting the ISO and the compressed file, using the bootinst.sh script.
In either case, the USB won't boot.
I tried both with Slax kernel and the system kernel, tried formatting the USB to ext4 and fat32 (although I boot in legacy mode).
I checked the bootfiles dir tree and, all the files are there.
The sructure of my decompressed ISO is identical to the working Slax ISO.
I'll try to repeat the process this week to see if I get better results.

**Comment by equetzal** [comment]
Ok, but just to be clear. You're not able to reach the bootloader, right?

**Comment by maccagnan** [comment]
Yes, the laptop BIOS does not seem to find the boot file (maybe eltorito or the mbr). The USB is set as the first boot option in the BIOS menu, the USB is active (led flashing) but the ISO won't boot.

**Comment by Tomas-M** [comment]
Slax does not support dd-ing to the target USB, so I really do not understand how could Slax work on the USB at the first place. I'm not sure if this issue is still relevant so I'm closing it
