### ISSUE TITLE
Installing from Bootable USB

### ISSUE THREAD

**Issue by maxy-walker** [Tomas-M/linux-live#44]
Hi, thanks for the excellent scripts, it worked very well for creation of the bootable USB, however I am unsure how to install my custom build to a host workstation after booting from the USB. Am I missing something? or is this not possible?

Thanks again,

John

**Comment by Tomas-M** [comment]
The goal is to make it bootable from the USB all the time, not to install it.

**Comment by secsonthebeach** [comment]
Hello, I appreciate this tool and the work going into it. I am currently working through using this for my needs, making a "grab & go" image for a specific purpose. Something that can be installed would be a big plus. Besides still addressing some bugs with using linux-live normally, I am currently reading through this with thoughts of how to include an installer.

https://help.ubuntu.com/community/MakeALiveCD/DVD/BootableFlashFromHarddiskInstall

Since much of this is out of my wheelhouse, any thoughts on if this could be included in a linux-live setup would be appreciated.
