### ISSUE TITLE
fbprintscreen

### ISSUE THREAD

**Issue by saymoncoppi** [Tomas-M/linux-live#59]
Hello Peter and Thomas!
I wa thinking about this fbprintscreen tool and I'd like to suggest some additions:
- Allow to select an area to take the screenshot;
- Insert a delay option.

About the selectable area I found this:
https://github.com/lolilolicon/xrectsel
https://youtu.be/m9QvpOUDY4w?t=71

And delay its a sleep at the code. If you guys likethe idea, I could help to code it. 
Best regards

**Comment by saymoncoppi** [comment]
A few other ideas:
- notify action event
- add timestamp at the file

https://www.reddit.com/r/unix/comments/8mlm8p/a_script_for_recording_gifs_with_xrectsel_gdialog/

**Comment by Tomas-M** [comment]
Hello,
when a PrintScreen key is pressed, the user expects to get the current screen, nothing else. If the user needs more power, he or she can install some more advanced application for that purpose. So I'm closing this ticket.

**Comment by Tomas-M** [comment]
Rough? I do not understand.
I read your two posts. I think it is very good idea to allow the user select a region of the screen, or add delay.  I appreciate your suggestions and I considered to include both your suggestions in Slax.

A bit later I realized that there are already applications for that task, which can be installed with 'apt'.
I come to the conclusion that existing apps may provide much more useful features for the user than anything I would code myself, so I decided to keep the behavior in Slax as it is now.

Maybe if I described my inner feelings and motives more precisely, my message would not appear rude to you. Unfortunately I receive lots of suggestions and other emails and I cannot explain my inner workings every time, since it is time consuming, but at least I replied to let you know that I read your suggestion. Take care :-)
