### ISSUE TITLE
Trouble with network

### ISSUE THREAD

**Issue by scorpioRED** [Tomas-M/linux-live#68]
After creating a USB flash drive (from Lubuntu) I have a problem with the network.
Computer won't get the IP address, however, before creating  bootable USB Drive, there is no any problem with it

**Comment by silvanet123** [comment]
I am using Ubuntu 19.04 had similar issues.  The issue is that netplan, the network configuration tools,  used the original name of the ethernet card (ens32, etc) which can change from system to system.  What I wanted was that the names would be eth0, eth1, wlan0, wlan1, etc like older versions of linux used to do.     I added the following boot options into the append line of syslinux.cfg: "net.ifnames=0 biosdevnames=0".  In netplan I changed ens32 change to eth0.    This helped with network working on other computers.
