### ISSUE TITLE
Is there any way to make the encrypted image?

### ISSUE THREAD

**Issue by scorpioRED** [Tomas-M/linux-live#78]
I mean mount only if booting from created  linux-live flash drive, and do not allow mount if connet to other system

**Comment by computermaster0101** [comment]
Hello! I was also curious about this after reading your question. I was able to find [this](https://ubuntuforums.org/showthread.php?t=1428720) which sounds like it might relate - i havent done any testing yet but would be curious to find out if your able to get it to work. I'll also do some testing on my side as my schedule allows. It sounds like if the squashfs image is encrypted, there will be a slight performance hit due to decryption but it shouldnt make the system unusable.

**Comment by Tomas-M** [comment]
I believe that @scorpioRED means something different. He probably means to have a partition on disk encrypted, and the partition would automatically mount when linux-live-based distro is started.

This is technically possible. There is no need for support in linux-live kit, since everything would be handled by the distribution which starts by using the linux-live scripts.
